### ISSUE TITLE
How do I make RefData for other species?

### ISSUE THREAD

**Issue by zhang-shilong** [YingZhou001/Immuannot#1]
Hello!

This is great work and I hope to use this software in my project.

I have an assembly of non-human species and I would like to annotate the MHC region with the [IPD-MHC](https://www.ebi.ac.uk/ipd/mhc/) database. How do I generate RefData based on the information in the IPD-MHC? Could you please provide an instruction document?

Thank you!

**Comment by YingZhou001** [comment]
Hi Shilong,

Thanks for using Immuannot. 
Regarding the difference between human and non-human species IPD data, the current version of reference construction pipeline can only support IPD/HLA dataset.  We will consider including the non-human species in the future. 

Best,
Ying

**Comment by zhang-shilong** [comment]
That's great. Thanks for the reply.

**Comment by yeeus** [comment]
@YingZhou001 
I have used Immuannot to annotate HLA genes in great apes with human IPD data as reference. So do you have some advice about the parameters (`overlaprate` and `diff`)?

**Comment by YingZhou001** [comment]
Sorry to the delayed reply.
Thanks for exploring Immuannot on great apes,  you may reduce "overlaprate" and increase "diff" because larger difference between human and great apes. I would try to set "overlaprate" to 0.5 and "diff" to 0.1 to see what will happen.
Honestly I haven't tried those yet but I will definitely work on the non-human species in the future.
