### ISSUE TITLE
Error: getopt: illegal option -- n

### ISSUE THREAD

**Issue by hangsuUNC** [YingZhou001/Immuannot#3]
Hi Ying,
I was trying to run the test example in the repository but have an error :`getopt: illegal option -- n`. I was running this in my mac.

Could you please provide suggestions about this?

Thanks,

Hang

**Comment by YingZhou001** [comment]
Hi Hang,

Immuannot was developed and tested under a linux environment. I haven't tested it under mac system yet, I guess it needs some more adjustments. Since immuannot is majorly built on minimap2, python3  and bash, I think it does not need lots of work. I will let you know if we have a mac version.

Best,
Ying

**Comment by hangsu01** [comment]
Thank you!

Hang

**Comment by hangsuUNC** [comment]
Thank you!
